name: Deploy to Google Cloud Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: gcpgithubactions
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy helloWorld \
            --gen2 \
            --runtime=nodejs18 \
            --region=us-central1 \
            --trigger-http \
            --allow-unauthenticated \
            --entry-point=helloWorld \
            --source=.
